=== albin-trainer/oracle_batch_17_2025/code base/5-XML/DTD/customer.dtd
<!ELEMENT customers (customer*)>
<!ELEMENT customer (id,cname,email,phoneNo?,address,orders?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phoneNo (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT orders (order+)>
<!ELEMENT order (orderid,orderdate,totalAmt)>
<!ELEMENT orderid (#PCDATA)>
<!ELEMENT orderdate (#PCDATA)>
<!ELEMENT totalAmt (#PCDATA)>
<!ATTLIST customer type CDATA #FIXED "prime">

=== albin-trainer/oracle_batch_17_2025/code base/5-XML/DTD/customers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE customers SYSTEM "customer.dtd">
<customers>
		<customer type="prime">  <!--  0 or more customer -->
			<id>1</id>
			<cname>Arjun</cname>
			<email>arjun@abc.com</email>
			<phoneNo>1234556</phoneNo> <!--  optional -->
			<address>Bangalore</address>
			<orders> <!--  0 or 1 orders -->
				<order> <!--  1 or more order -->
					<orderid>991</orderid>
					<orderdate>5-5-25</orderdate>
					<totalAmt>10000</totalAmt>
				</order>
				<order>
					<orderid>992</orderid>
					<orderdate>1-1-25</orderdate>
					<totalAmt>5000</totalAmt>
				</order>
			</orders>
		</customer>
		<customer>
			<id>2</id>
			<cname>Sanjay</cname>
			<email>sanjay@abc.com</email>
			<address>Mumbai</address>
		</customer>
</customers>
