=== albin-trainer/oracle_batch_17_2025/code base/5-XML/xsd/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/orders" xmlns:tns="http://www.example.org/orders" elementFormDefault="qualified">

    <element name="customerorders" type="tns:customerorders"></element>
    
    <complexType name="customerorders">
    	<sequence>
    		<element name="customers" type="tns:customers"></element>
    		<element name="orders" type="tns:orders"></element>
    	</sequence>
    </complexType>

    <complexType name="customers">
    	<sequence>
    		<element name="customer" type="tns:customer" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="customer" >
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="address" type="string"></element>
    	</sequence>
    	<attribute name="id" type="ID"></attribute>
    </complexType>

    <complexType name="orders">
    	<sequence>
    		<element name="order" type="tns:order" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="order">
    	<sequence>
    		<element name="amoint" type="string"></element>
    	</sequence>
    	<attribute name="orderid" type="ID"></attribute>
    	<attribute name="cid" type="IDREF"></attribute>
    </complexType>
</schema>

=== albin-trainer/oracle_batch_17_2025/code base/5-XML/xsd/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<customerorders xmlns="http://www.example.org/orders" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/orders orders.xsd ">
  <customers>
    <customer id="C1">
      <name>name</name>
      <address>address</address>
    </customer>
     <customer id="C2">
      <name>name</name>
      <address>address</address>
    </customer>
  </customers>
  <orders>
    <order orderid="OR1" cid="C1">
      <amoint>amoint</amoint>
    </order>
    <order orderid="OR2" cid="C2">
      <amoint>amoint</amoint>
    </order>
    <order orderid="OR3" cid="C1">
      <amoint>amoint</amoint>
    </order>
  </orders>
</customerorders>
